general:
  project: leonardo_stage1
  run: slimpajama_30B
  seed: 42
  ignore_sanity_checks: false

model:
  make_vocab_size_divisible_by: 128
  model_config:
    is_llama_config: true
    hidden_size: 1024
    num_hidden_layers: 16
    num_attention_heads: 16
    num_key_value_heads: 16
    intermediate_size: 2752
    max_position_embeddings: 2048
    hidden_act: silu
    rms_norm_eps: 1.0e-05
    rope_theta: 10000.0
    tie_word_embeddings: true
    vocab_size: 128256 # Llama 3
    initializer_range: 0.02

optimizer:
  accumulate_grad_in_fp32: true
  clip_grad: 1.0
  learning_rate_scheduler:
    learning_rate: 0.0005
    lr_decay_style: cosine
    lr_warmup_steps: 1000
    min_decay_lr: 5.0e-05 # Δεν μηδενίζουμε για να συνεχίσουμε Stage 2
  optimizer_factory:
    name: adamW
    torch_adam_is_fused: true
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
  weight_decay: 0.1
  zero_stage: 0

parallelism:
  dp: 4
  tp: 1
  pp: 1
  tp_mode: REDUCE_SCATTER

data_stages:
- name: Stage 1 - SlimPajama Packed
  start_training_step: 1
  data:
    dataset:
      dataset_overwrite_cache: false
      # Εδώ θα βάλουμε το path του τοπικού NVMe 
      dataset_path: /tmp/slimpajama_local/train 
      text_column_name: input_ids
  num_loading_workers: 4
  seed: 42

tokens:
  sequence_length: 2048
  micro_batch_size: 32
  batch_accumulation_per_replica: 2
  
  # GBS = 256 seqs -> 0.5M tokens/step
  # 30B Tokens / 0.5M = 60,000 steps
  train_steps: 60000
  
  val_check_interval: 2000
  limit_val_batches: 50

checkpoints:
  checkpoint_interval: 2000
  checkpoints_path: /scratch/$USER/ckpts/stage1
  save_initial_state: false
  checkpoints_path_is_shared_file_system: true

logging:
  iteration_step_info_interval: 10
  log_level: info